// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package upload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UploadHandlerClient is the client API for UploadHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadHandlerClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (UploadHandler_UploadClient, error)
}

type uploadHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadHandlerClient(cc grpc.ClientConnInterface) UploadHandlerClient {
	return &uploadHandlerClient{cc}
}

func (c *uploadHandlerClient) Upload(ctx context.Context, opts ...grpc.CallOption) (UploadHandler_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &UploadHandler_ServiceDesc.Streams[0], "/UploadHandler/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &uploadHandlerUploadClient{stream}
	return x, nil
}

type UploadHandler_UploadClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type uploadHandlerUploadClient struct {
	grpc.ClientStream
}

func (x *uploadHandlerUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uploadHandlerUploadClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UploadHandlerServer is the server API for UploadHandler service.
// All implementations must embed UnimplementedUploadHandlerServer
// for forward compatibility
type UploadHandlerServer interface {
	Upload(UploadHandler_UploadServer) error
	mustEmbedUnimplementedUploadHandlerServer()
}

// UnimplementedUploadHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedUploadHandlerServer struct {
}

func (UnimplementedUploadHandlerServer) Upload(UploadHandler_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedUploadHandlerServer) mustEmbedUnimplementedUploadHandlerServer() {}

// UnsafeUploadHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadHandlerServer will
// result in compilation errors.
type UnsafeUploadHandlerServer interface {
	mustEmbedUnimplementedUploadHandlerServer()
}

func RegisterUploadHandlerServer(s grpc.ServiceRegistrar, srv UploadHandlerServer) {
	s.RegisterService(&UploadHandler_ServiceDesc, srv)
}

func _UploadHandler_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploadHandlerServer).Upload(&uploadHandlerUploadServer{stream})
}

type UploadHandler_UploadServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type uploadHandlerUploadServer struct {
	grpc.ServerStream
}

func (x *uploadHandlerUploadServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uploadHandlerUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UploadHandler_ServiceDesc is the grpc.ServiceDesc for UploadHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UploadHandler",
	HandlerType: (*UploadHandlerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _UploadHandler_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "upload.proto",
}
